spring.config.import=optional:file:.env[.properties]

spring.application.name=api

spring.jpa.open-in-view=true

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

api.security.token.secret=${JWT_SECRET}