spring.config.activate.on-profile=dev
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/aluggy_dev
spring.datasource.username=aluggy
spring.datasource.password=aluggy123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/aluggy_dev
spring.flyway.user=aluggy
spring.flyway.password=aluggy123
spring.flyway.locations=classpath:db/migration/postgresql